default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gospeltribes
  host: localhost

test:
  <<: *default
  database: boastload-ws_test
  username: postgres
  password: password
  host: localhost

staging:
  <<: *default
  database: boastload-ws_staging
  url: <%= ENV["DATABASE_URL"] %>


production:
  <<: *default
  # database: boastload-ws_production
  database: gospeltribes
  url: <%= ENV["DATABASE_URL"] %>
